desiderata/urls.py
from django.urls import path
from desiderata import views

app_name = 'desiderata'

urlpatterns = [
    path('detail/<desiderata_slug>', views.DetailView.as_view(), name='detail'),
    path('all', views.DesiderataListView.as_view(), name='all'),
]

good_tests/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('home.urls', namespace='home')),
    path('desideratas/', include('desiderata.urls', namespace='desiderata')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

desiderata/models.py
from django.db import models
from autoslug import AutoSlugField
from tinymce.models import HTMLField

class Desiderata(models.Model):

    slug = AutoSlugField(populate_from='name')
    name = models.CharField(max_length=256)
    video = models.CharField(max_length=1024, null=True)
    description = HTMLField(null=True, blank=True)
    ordering = models.IntegerField(default=0)

    class Meta:
        ordering = ['ordering', 'name']

    @staticmethod
    def example():
        return Desiderata(
            name='Desiderata-Name',
            description='Desiderata-Description')

    def with_ordering(self, ordering):
        self.ordering = ordering
        return self

    def with_name(self, name):
        self.name = name
        return self

    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

desiderata/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from desiderata.models import Desiderata

class DetailView(View):

    def get(self, request, desiderata_slug, *args, **kwargs):
        desiderata = get_object_or_404(Desiderata, slug=desiderata_slug)
        context = {
            'desiderata': desiderata
        }
        return render(request, 'desiderata/detail.html', context)

class DesiderataListView(View):

    def get(self, request, *args, **kwargs):
        context = {
            'desideratas': Desiderata.objects.all()
        }
        return render(request, 'desiderata/all.html', context)

home/views.py
from django.shortcuts import render
from django.views import View

class HomeView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'home/home.html')

desiderata/templates/desiderata/_youtube_video.html
{% load youtube %}
<iframe 
    width="560" 
    height="315" 
    src="{{desiderata.video|embedded_youtube_url}}" 
    frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>

desiderata/templates/desiderata/all.html
<html>
<body>
<ul>
{% for desiderata in desideratas %}
<li>
    <a href="{% url 'desiderata:detail' desiderata.slug %}">
        {{desiderata.name}}
    </a>
</li>
{% endfor %}
</ul>
</body>
</html>

desiderata/templates/desiderata/detail.html
<html>
  <body>
    <div class="desiderata">
      <h1 class="name">{{desiderata.name}}</h1>
      <div class="video">
        {% include 'desiderata/_youtube_video.html' %}
      </div>
      <div class="description">{{desiderata.description|safe}}</div>
    </div>
  </body>
</html>

home/templates/home/home.html
{% extends 'base.html' %}
{% comment %} <html>

<body>
<nav>
    <ul>
        <li><a href="{% url 'desiderata:all' %}">Desideratas</a></li>
    </ul>
</nav>
<h1>Good Tests</h1>
</body>
</html> {% endcomment %}